### ISSUE TITLE
Nested query inside from clause without using >>> token

### ISSUE THREAD

**Issue by Hayanesh** [mnesimiyilmaz/sql4json#2]
Hi @mnesimiyilmaz, 
      I recently had the opportunity to explore this project for yours and wanted to express my admiration for the exceptional work you've done. Your project has undoubtedly caught my interest.  On further looking into the code, saw that you have used '>>>' to indicate a nested query instead of standard SQL format of ( ie. SELECT * FROM (SELECT * FROM $r)). 

Can we also add support for this?

**Comment by Hayanesh** [comment]
Just gave an attempt to see if if this can be done. https://github.com/mnesimiyilmaz/sql4json/pull/1

Please take a look.

Regards,
Hayanesh

**Comment by mnesimiyilmaz** [comment]
Hi @Hayanesh,
Thank you so much for your effort and time. I merged your changes.
Regards,
Mucahit
